###############################################################
#
# Config File for INVISIBLE UNIVERSITY flavour of VITALITY bootstrap theme
#
#--------------------------------------------------------------
BaseURL = "https://homeypages.github.io/homey.berlin/"
LanguageCode = "de-DE"
Title = "Homey Pages - Personal Websites"
Theme = "hugo-university-theme"
publishDir = "docs"

[Params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# To provide some metadata for search engines feel free to add a few
  # information about you and your website.

  Flavour = "university"
	Style = "modern"

	# !Important: Theme colors can be selected in static/less/vitality.less

	Name = "HomeyPages"
	Description = "Very Personal Websites"
	Favicon = "favicon.ico"
	Author = "Lafisrap (Michael Schmidt)"
	Brand = "Homey Pages --- Tallinn - Berlin"

	# List of Google fonts, for use in less files.
	#
	# TIPP! To find fonts:
	# - Go to fonts.google.com.
	# - Select a font, open the selected font at the bottom of the page, maybe customize it
	# - In section "Embed Font" copy the full family value (boldly printed), everything after 'family='.
	# - Add it in quotation marks to the list below.
	#
	# TIPP! A good first step after defining fonts, would be to go to static/less/vitality.less and define the main fonts.

	Fonts = [
		"IM+Fell+English+SC&amp;subset=latin-ext",
		"Josefin+Sans:300,300i,400,400i,700,700i",
		"Cabin+Condensed:400,500,600,700",
		"Caveat:400,700",
		"Kalam:300,400,700",
		"Assistant:200,300,400,600,700,800",
		"Cormorant+Upright:300,400,500,600,700|Expletus+Sans:400,400i,500,500i,600,600i,700,700i|Kalam:300,400,700|Zeyada",
	]

	# If you want to have your fonts local, you have to place them in static/fonts folder
	FontsLocal = true
